module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
  printWidth: 85,
  tabWidth: 2,
  singleQuote: true,
  semi: false,
  trailingComma: 'all',
  jsxBracketSameLine: true,
  arrowParens: 'avoid',
  embeddedLanguageFormatting: 'auto',
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  htmlWhitespaceSensitivity: 'strict',
  proseWrap: 'always',
}
