module.exports = {
  plugins: ['prettier-plugin-tailwindcss'],
  singleQuote: true,
  semi: false,
  trailingComma: 'all',
  // tabWidth: 2,
  // printWidth: 85,
  // jsxBracketSameLine: true,
  // arrowParens: 'avoid',
  // embeddedLanguageFormatting: 'auto',
  // jsxSingleQuote: false,
  // bracketSpacing: true,
  // bracketSameLine: false,
  // htmlWhitespaceSensitivity: 'strict',
  // proseWrap: 'always',
}
