version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wildOasis-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wildOasis-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@wildOasis-db:5432/thewildoasis
      - PORT=8080
    depends_on:
      - db
    entrypoint: [ "sh", "-c", "npx prisma migrate deploy --schema=./src/models/prisma/schema.prisma && npm start" ]

  db:
    image: postgres:13
    container_name: wildOasis-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thewildoasis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
