version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wildOasis-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

#  server:
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    container_name: wildOasis-server
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./server:/app
#      - /app/node_modules
#    environment:
#      - NODE_ENV=development
#    depends_on:
#      - client
