version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wildOasis-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wildOasis-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/thewildoasis
    depends_on:
      - prisma
    env_file:
      - ./server/.env

  prisma:
    image: prismagraphql/prisma:1.34.10
    platform: linux/amd64
    environment:
      PRISMA_CONFIG_PATH: /app/prisma.yml
    volumes:
      - ./server/src/models/prisma:/app

  db:
    image: postgres:13
    container_name: wildOasis-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thewildoasis
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
